In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv


In [3]:
df = pd.read_csv('train.csv')

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (891, 12)


In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [7]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Missing Percentage': missing_percentage.round(2)
})

missing_report

,Missing Values,Missing Percentage
PassengerId,0,0.00
Survived,0,0.00
Pclass,0,0.00
Name,0,0.00
Sex,0,0.00
Age,177,19.87
SibSp,0,0.00
Parch,0,0.00
Ticket,0,0.00
Fare,0,0.00


In [8]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0


In [9]:
for column in df.columns:
    print("\nColumn:", column)
    print(df[column].unique()[:20])


Column: PassengerId
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Column: Survived
[0 1]

Column: Pclass
[3 1 2]

Column: Name
['Braund, Mr. Owen Harris'
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
 'Heikkinen, Miss. Laina' 'Futrelle, Mrs. Jacques Heath (Lily May Peel)'
 'Allen, Mr. William Henry' 'Moran, Mr. James' 'McCarthy, Mr. Timothy J'
 'Palsson, Master. Gosta Leonard'
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'
 'Nasser, Mrs. Nicholas (Adele Achem)' 'Sandstrom, Miss. Marguerite Rut'
 'Bonnell, Miss. Elizabeth' 'Saundercock, Mr. William Henry'
 'Andersson, Mr. Anders Johan' 'Vestrom, Miss. Hulda Amanda Adolfina'
 'Hewlett, Mrs. (Mary D Kingcome) ' 'Rice, Master. Eugene'
 'Williams, Mr. Charles Eugene'
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)'
 'Masselmani, Mrs. Fatima']

Column: Sex
['male' 'female']

Column: Age
[22. 38. 26. 35. nan 54.  2. 27. 14.  4. 58. 20. 39. 55. 31. 34. 15. 28.
  8. 19.]

Column: SibSp
[1 0 3 4 2 5 8]


In [10]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [11]:
categorical_columns = df.select_dtypes(include='object').columns

for column in categorical_columns:
    print("\n", column)
    print(df[column].value_counts(dropna=False))


 Name
Name
Dooley, Mr. Patrick                                    1
Braund, Mr. Owen Harris                                1
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    1
Heikkinen, Miss. Laina                                 1
Futrelle, Mrs. Jacques Heath (Lily May Peel)           1
                                                      ..
Hewlett, Mrs. (Mary D Kingcome)                        1
Vestrom, Miss. Hulda Amanda Adolfina                   1
Andersson, Mr. Anders Johan                            1
Saundercock, Mr. William Henry                         1
Bonnell, Miss. Elizabeth                               1
Name: count, Length: 891, dtype: int64

 Sex
Sex
male      577
female    314
Name: count, dtype: int64

 Ticket
Ticket
347082              7
1601                7
CA. 2343            7
3101295             6
CA 2144             6
                   ..
PC 17590            1
17463               1
330877              1
373450              1
STON/O2. 3101282    1


In [12]:
missing = df.isnull().sum()

print("Missing values before cleaning:")
print(missing[missing > 0])

Missing values before cleaning:
Age         177
Cabin       687
Embarked      2
dtype: int64


In [13]:
age_median = df['Age'].median()

df['Age'] = df['Age'].fillna(age_median)

print("Missing Age values after cleaning:", df['Age'].isnull().sum())
print("Age values filled using median:", age_median)



Missing Age values after cleaning: 0
Age values filled using median: 28.0


In [14]:
embarked_mode = df['Embarked'].mode()[0]

df['Embarked'] = df['Embarked'].fillna(embarked_mode)

print("Missing Embarked values after cleaning:", df['Embarked'].isnull().sum())
print("Embarked values filled using mode:", embarked_mode)

Missing Embarked values after cleaning: 0
Embarked values filled using mode: S


In [15]:
df['Cabin'] = df['Cabin'].fillna('Unknown')

print("Missing Cabin values after cleaning:", df['Cabin'].isnull().sum())

Missing Cabin values after cleaning: 0


In [16]:
print("Missing values after Step 3:")
print(df.isnull().sum())

Missing values after Step 3:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64


In [17]:
# ================================
# STEP 4: COMPLETE DATA CLEANING
# ================================

# 1. Check and remove duplicate rows
duplicates_before = df.duplicated().sum()
df = df.drop_duplicates()
duplicates_after = df.duplicated().sum()

print("Duplicate rows before cleaning:", duplicates_before)
print("Duplicate rows after cleaning:", duplicates_after)


# 2. Standardize categorical columns
# Remove unnecessary spaces and standardize text
for column in ['Sex', 'Embarked']:
    df[column] = df[column].astype(str).str.strip()

df['Sex'] = df['Sex'].str.lower()
df['Embarked'] = df['Embarked'].str.upper()

print("\nUnique Sex values:", df['Sex'].unique())
print("Unique Embarked values:", df['Embarked'].unique())


# 3. Correct data types
df['PassengerId'] = df['PassengerId'].astype(int)
df['Survived'] = df['Survived'].astype(int)
df['Pclass'] = df['Pclass'].astype(int)
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['SibSp'] = pd.to_numeric(df['SibSp'], errors='coerce')
df['Parch'] = pd.to_numeric(df['Parch'], errors='coerce')
df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce')


# 4. Check logical ranges
print("\nRange checks:")
print("Age range:", df['Age'].min(), "to", df['Age'].max())
print("Fare range:", df['Fare'].min(), "to", df['Fare'].max())
print("Pclass values:", sorted(df['Pclass'].unique()))
print("Survived values:", sorted(df['Survived'].unique()))


# 5. Outlier detection using IQR
numeric_columns = ['Age', 'Fare', 'SibSp', 'Parch']

outlier_report = {}

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = ((df[column] < lower_bound) |
                (df[column] > upper_bound)).sum()

    outlier_report[column] = outliers

print("\nOutlier count:")
print(outlier_report)


# 6. Cap extreme outliers using IQR
# This keeps the records instead of deleting them.

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[column] = df[column].clip(lower=lower_bound, upper=upper_bound)

print("\nOutliers have been capped using the IQR method.")

print("\nCleaning completed successfully!")

Duplicate rows before cleaning: 0
Duplicate rows after cleaning: 0

Unique Sex values: ['male' 'female']
Unique Embarked values: ['S' 'C' 'Q']

Range checks:
Age range: 0.42 to 80.0
Fare range: 0.0 to 512.3292
Pclass values: [np.int64(1), np.int64(2), np.int64(3)]
Survived values: [np.int64(0), np.int64(1)]

Outlier count:
{'Age': np.int64(66), 'Fare': np.int64(116), 'SibSp': np.int64(46), 'Parch': np.int64(213)}

Outliers have been capped using the IQR method.

Cleaning completed successfully!


In [18]:
# ==========================================
# STEP 5: BEFORE vs AFTER QUALITY REPORT
# ==========================================

quality_report = pd.DataFrame({
    'Metric': [
        'Number of Rows',
        'Number of Columns',
        'Missing Values',
        'Duplicate Rows'
    ],
    'After Cleaning': [
        len(df),
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

print("DATA QUALITY REPORT AFTER CLEANING")
display(quality_report)

print("\nMissing values by column:")
display(df.isnull().sum())

print("\nData types after cleaning:")
display(df.dtypes)

DATA QUALITY REPORT AFTER CLEANING


,Metric,After Cleaning
0,Number of Rows,891
1,Number of Columns,12
2,Missing Values,0
3,Duplicate Rows,0



Missing values by column:


,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,0
SibSp,0
Parch,0
Ticket,0
Fare,0



Data types after cleaning:


,0
PassengerId,int64
Survived,int64
Pclass,int64
Name,object
Sex,object
Age,float64
SibSp,float64
Parch,int64
Ticket,object
Fare,float64


In [19]:
# ==========================================
# STEP 6: FINAL CLEANED DATASET
# ==========================================

print("Final dataset shape:", df.shape)

print("\nFirst 5 rows:")
display(df.head())

print("\nFinal missing values:")
print(df.isnull().sum())

print("\nFinal duplicate count:", df.duplicated().sum())

# Save cleaned dataset
df.to_csv('titanic_cleaned.csv', index=False)

print("\nCleaned dataset saved successfully as: titanic_cleaned.csv")

Final dataset shape: (891, 12)

First 5 rows:


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0,PC 17599,65.6344,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0.0,0,373450,8.0500,Unknown,S



Final missing values:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Final duplicate count: 0

Cleaned dataset saved successfully as: titanic_cleaned.csv


# Titanic Dataset Cleaning and Preprocessing

## Project Overview

This project focuses on cleaning and preprocessing the Titanic dataset to improve its data quality and prepare it for further analysis.

The dataset was inspected for missing values, duplicate records, inconsistent formatting, data type issues, and numerical outliers.

## Objectives

- Identify data quality issues.
- Handle missing values appropriately.
- Check and remove duplicate records.
- Standardize inconsistent categorical values.
- Detect and handle numerical outliers using the IQR method.
- Verify and correct data types.
- Create a clean dataset ready for analysis.

## Dataset Cleaning Decisions

### Missing Values
- Missing values in `Age` were filled using the median.
- Missing values in `Embarked` were filled using the mode.
- Missing values in `Cabin` were replaced with `Unknown`.

### Duplicate Records
Duplicate rows were checked and removed if present.

### Data Standardization
The `Sex` column was standardized to lowercase, while the `Embarked` column was standardized to uppercase.

### Outliers
Outliers in numerical columns were detected using the Interquartile Range (IQR) method. Extreme values were capped instead of removing records to preserve valid passenger information.

## Conclusion

The Titanic dataset was successfully cleaned and prepared for further analysis. Missing values, duplicates, formatting inconsistencies, data types, and numerical outliers were addressed.

The final cleaned dataset is suitable for exploratory analysis and machine learning applications.

In [20]:
# Create Before vs After Data Quality Summary

before_rows = 891
before_missing = 866   # Age 177 + Cabin 687 + Embarked 2
before_duplicates = 0

after_rows = len(df)
after_missing = df.isnull().sum().sum()
after_duplicates = df.duplicated().sum()

before_after = pd.DataFrame({
    'Metric': [
        'Number of Rows',
        'Missing Values',
        'Duplicate Rows',
        'Data Types Checked',
        'Outliers Handled'
    ],
    'Before Cleaning': [
        before_rows,
        before_missing,
        before_duplicates,
        'Original',
        'Not Handled'
    ],
    'After Cleaning': [
        after_rows,
        after_missing,
        after_duplicates,
        'Corrected',
        'Handled using IQR Capping'
    ]
})

display(before_after)

,Metric,Before Cleaning,After Cleaning
0,Number of Rows,891,891
1,Missing Values,866,0
2,Duplicate Rows,0,0
3,Data Types Checked,Original,Corrected
4,Outliers Handled,Not Handled,Handled using IQR Capping


In [21]:
from google.colab import files

files.download('titanic_cleaned.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>